### ISSUE TITLE
After stoping and resuming training, the delta file is trained from scratch(small file size)

### ISSUE THREAD

**Issue by bananasss00** [guaneec/custom-diffusion-webui#7]
title

**Comment by guaneec** [comment]
The `.optim` files you mean? Haven't implemented that yet, will fix in an upcoming update supporting multi-concept training.

**Comment by bananasss00** [comment]
> The .optim files you mean?

.delta.safetensors files

![изображение](https://user-images.githubusercontent.com/30229634/218050962-f69d1b67-3f7a-41dc-94cd-efe55fbe20b2.png)

latest file size was 2mb, after stoping/resuming training file size start from 300kb

PS: Or is that how it should be?

**Comment by guaneec** [comment]
I have not yet implemented storing delta weights to the `.optim` file, so resuming would only load the text embeddings but not the delta weights, effectively resetting deltas to zero. The `.delta.safetensors` files becoming smaller is a curious side effect - as the dimensions of the low rank decomposition is dynamic, seems like earlier in training the singular values are more concentrated, so the info can be stored in smaller matrices.

Anyways, I'm working on a new storage format that stores the embeddings and delta weights in the same file. Expect this to be fixed in a few days max.

**Comment by bananasss00** [comment]
got it, thanks a lot for your work
